#!/bin/bash

# Run me to cleanup an instance before baking an AMI

# It cleans up common changes which are introduced
# to a instance in the process of logging on
# You will need to remove any additional changes manually

# User who was auto generated by rc.local
USER=ec2-user

export HISTSIZE=0

echo "Removing host keys"
sudo /bin/rm -rf /etc/ssh/ssh_host*_key*

echo "Removing $USER authorized keys"
/bin/cp /dev/null /home/$USER/.ssh/authorized_keys
chmod 600 /home/$USER/.ssh/authorized_keys

echo "Cleaning up /var/log"
/bin/cp /dev/null /var/log/secure
/bin/cp /dev/null /var/log/messages
/bin/cp /dev/null /var/log/dmesg
/bin/cp /dev/null /var/log/wtmp
/bin/cp /dev/null /var/log/lastlog
/bin/cp /dev/null /var/log/cron
/bin/rm -f /var/log/*.log

echo "Cleaning up tmp files"
/bin/rm -fr /var/tmp/* /tmp/*

echo "Removing faillog"
/usr/bin/faillog -r

echo "Removing bash_history"
/bin/rm -f /root/.bash_history /home/$USER/.bash_history /home/ea/.bash_history

echo "Removing chef logs"
/bin/rm -fr /var/log/chef/chef.log

echo 'Removing everything from /root'
/bin/rm -fr /root/* /root/.s3cfg

echo 'Shutting down instance'
/sbin/init 0
